apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: default-petstore-8080
  namespace: gloo-system
spec:
  discoveryMetadata:
    labels:
      service: petstore
  kube:
    selector:
      app: petstore
    serviceName: petstore
    serviceNamespace: default
    servicePort: 8080
  # ----- Health Check (a.k.a. active health checks) -------
  healthChecks:
  - healthyThreshold: 1
    httpHealthCheck:
      path: /api/pets
    interval: 1s
    timeout: 1s
    unhealthyThreshold: 1
    reuseConnection: false
    noTrafficInterval: 5s # Start sending health checks after 5 seconds (default is 60)
  # ----- Outlier Detection  (a.k.a. passive health checks) ------
  outlierDetection:
    consecutive5xx: 1
    maxEjectionPercent: 50
    interval: 1s
  circuitBreakers:
    maxRetries: 100 # Number of concurrent retries
  # ----- Help with consistency between the Kubernetes control-plane and the Gloo control-plane ------
  ignoreHealthOnHostRemoval: true